# This is a sample secrets file that would be used in Streamlit Cloud
# You can add and manage secrets through the Streamlit Cloud dashboard

[job_boards]
default_boards = ["indeed", "linkedin"]
default_country = "USA"

[app_settings]
app_name = "Lucy - Job Search Aggregator"
default_results = 5
default_hours = 72
enable_analytics = false 